// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511110226_AddStreaksAndAchivements")]
    partial class AddStreaksAndAchivements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Пройти первый урок",
                            Emoji = "🎯",
                            Key = "first_lesson",
                            Title = "Первый шаг"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Набрать 50 XP",
                            Emoji = "⚡",
                            Key = "xp_50",
                            Title = "Новичок"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Набрать 200 XP",
                            Emoji = "📖",
                            Key = "xp_200",
                            Title = "Ученик"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Набрать 500 XP",
                            Emoji = "🧠",
                            Key = "xp_500",
                            Title = "Знаток"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Пройти 5 уроков",
                            Emoji = "📚",
                            Key = "lessons_5",
                            Title = "Книжный червь"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Пройти 10 уроков",
                            Emoji = "💪",
                            Key = "lessons_10",
                            Title = "Усердный"
                        },
                        new
                        {
                            Id = 7,
                            Description = "3 дня подряд",
                            Emoji = "🔥",
                            Key = "streak_3",
                            Title = "Огонёк"
                        },
                        new
                        {
                            Id = 8,
                            Description = "7 дней подряд",
                            Emoji = "🏆",
                            Key = "streak_7",
                            Title = "Неделя силы"
                        });
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Что такое 1С и как она устроена",
                            Order = 1,
                            Title = "Введение в платформу"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Справочники, документы, регистры",
                            Order = 2,
                            Title = "Объекты конфигурации"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Description = "Получение данных из БД",
                            Order = 3,
                            Title = "Язык запросов"
                        });
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#7c3aed",
                            Description = "Фундамент платформы 1С:Предприятие",
                            Emoji = "🏗️",
                            Order = 1,
                            Title = "1С Основы"
                        });
                });

            modelBuilder.Entity("Backend.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            Description = "Введение в платформу",
                            DurationMinutes = 5,
                            Order = 1,
                            Title = "Что такое 1С?",
                            Topic = "1c-basics",
                            XpReward = 10
                        },
                        new
                        {
                            Id = 2,
                            Content = "",
                            Description = "Конфигуратор и режим предприятия",
                            DurationMinutes = 5,
                            Order = 2,
                            Title = "Интерфейс платформы",
                            Topic = "1c-basics",
                            XpReward = 15
                        },
                        new
                        {
                            Id = 3,
                            Content = "",
                            Description = "Хранение условно-постоянных данных",
                            DurationMinutes = 5,
                            Order = 3,
                            Title = "Справочники",
                            Topic = "1c-basics",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 4,
                            Content = "",
                            Description = "Хозяйственные операции",
                            DurationMinutes = 5,
                            Order = 4,
                            Title = "Документы",
                            Topic = "1c-basics",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 5,
                            Content = "",
                            Description = "Накопление и хранение данных",
                            DurationMinutes = 5,
                            Order = 5,
                            Title = "Регистры",
                            Topic = "1c-basics",
                            XpReward = 25
                        },
                        new
                        {
                            Id = 6,
                            Content = "",
                            Description = "Язык запросов 1С",
                            DurationMinutes = 5,
                            Order = 6,
                            Title = "Запросы",
                            Topic = "1c-basics",
                            XpReward = 30
                        });
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectIndex = 1,
                            Explanation = "1С:Предприятие — это платформа для разработки и запуска бизнес-приложений (конфигураций).",
                            LessonId = 1,
                            OptionsJson = "[\"Язык программирования\",\"Платформа для создания бизнес-приложений\",\"База данных\",\"Операционная система\"]",
                            Text = "Что такое 1С:Предприятие?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectIndex = 1,
                            Explanation = "Конфигуратор — это встроенная среда разработки платформы 1С:Предприятие.",
                            LessonId = 1,
                            OptionsJson = "[\"Visual Studio\",\"Конфигуратор\",\"Среда разработки\",\"IDE 1С\"]",
                            Text = "Как называется программа для разработки в 1С?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectIndex = 1,
                            Explanation = "Конфигурация — это прикладное решение (программа) созданное на платформе 1С. Например: 1С:Бухгалтерия, 1С:ЗУП.",
                            LessonId = 1,
                            OptionsJson = "[\"Настройки операционной системы\",\"Прикладное решение созданное на платформе 1С\",\"База данных пользователей\",\"Файл настроек\"]",
                            Text = "Что такое конфигурация в 1С?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectIndex = 1,
                            Explanation = "Режим предприятия — это пользовательский режим работы, где ведётся реальная работа с данными.",
                            LessonId = 2,
                            OptionsJson = "[\"Конфигуратор\",\"Режим предприятия\",\"Режим отладки\",\"Административный режим\"]",
                            Text = "В каком режиме работают обычные пользователи 1С?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectIndex = 1,
                            Explanation = "Конфигуратор — среда разработки где создаются справочники, документы, отчёты и другие объекты.",
                            LessonId = 2,
                            OptionsJson = "[\"В режиме предприятия\",\"В конфигураторе\",\"В консоли запросов\",\"В браузере\"]",
                            Text = "Где разработчик создаёт объекты конфигурации?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectIndex = 1,
                            Explanation = "Дерево конфигурации — панель в конфигураторе где отображаются все объекты: справочники, документы, регистры и т.д.",
                            LessonId = 2,
                            OptionsJson = "[\"Структура базы данных\",\"Дерево конфигурации\",\"Список объектов\",\"Иерархия классов\"]",
                            Text = "Как называется дерево объектов конфигурации в конфигураторе?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectIndex = 1,
                            Explanation = "Справочник хранит условно-постоянные данные — товары, контрагентов, сотрудников.",
                            LessonId = 3,
                            OptionsJson = "[\"Документ для записи операций\",\"Объект для хранения условно-постоянной информации\",\"Отчёт для вывода данных\",\"Регистр для накопления данных\"]",
                            Text = "Что такое Справочник в 1С?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectIndex = 1,
                            Explanation = "Каждый справочник автоматически имеет реквизиты Код и Наименование.",
                            LessonId = 3,
                            OptionsJson = "[\"Дата\",\"Код и Наименование\",\"Сумма\",\"Количество\"]",
                            Text = "Какой реквизит есть у каждого Справочника по умолчанию?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectIndex = 1,
                            Explanation = "В иерархических справочниках элементы группируются в Папки (группы).",
                            LessonId = 3,
                            OptionsJson = "[\"Документ\",\"Папка (группа)\",\"Регистр\",\"Константа\"]",
                            Text = "Как называется элемент справочника верхнего уровня при иерархии?"
                        });
                });

            modelBuilder.Entity("Backend.Models.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Streak");
                });

            modelBuilder.Entity("Backend.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            Description = "Обзор платформы",
                            Order = 1,
                            Title = "Что такое 1С?"
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 1,
                            Description = "Среда разработки",
                            Order = 2,
                            Title = "Конфигуратор"
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 2,
                            Description = "Условно-постоянные данные",
                            Order = 1,
                            Title = "Справочники"
                        },
                        new
                        {
                            Id = 4,
                            ChapterId = 2,
                            Description = "Хозяйственные операции",
                            Order = 2,
                            Title = "Документы"
                        },
                        new
                        {
                            Id = 5,
                            ChapterId = 3,
                            Description = "SELECT в языке 1С",
                            Order = 1,
                            Title = "Основы запросов"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Student");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievement");
                });

            modelBuilder.Entity("Backend.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCOmpleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.Lesson", b =>
                {
                    b.HasOne("Backend.Models.Topic", "TopicRef")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId");

                    b.Navigation("TopicRef");
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.HasOne("Backend.Models.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Backend.Models.Streak", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Topic", b =>
                {
                    b.HasOne("Backend.Models.Chapter", "Chapter")
                        .WithMany("Topics")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Backend.Models.UserAchievement", b =>
                {
                    b.HasOne("Backend.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserProgress", b =>
                {
                    b.HasOne("Backend.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Chapter", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Backend.Models.Lesson", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Models.Topic", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
